### ISSUE TITLE
Lua Error on login

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Journalator#15]
Version 0.51

2x ...eJournalator\Source\Archiving\Initialize.lua:45: attempt to perform arithmetic on local 'storeTime' (a nil value)
[string "@Journalator\Source\Archiving\Initialize.lua"]:45: in function `Initialize'
[string "@Journalator\Source\Initialize.lua"]:8: in function `Initialize'
[string "@Journalator\Journalator-0.51.lua"]:12: in function <Journalator\Journalator.lua:10>

Locals:
archive = <table> {
 initialized = true
 activeStores = <table> {
 }
 sv = <table> {
 }
 storeMap = <table> {
 }
 prototypes = <table> {
 }
}
storeTime = nil
currentTime = 1628274029
(*temporary) = 1628274029
(*temporary) = 1628274029
(*temporary) = 1628274029
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to perform arithmetic on local 'storeTime' (a nil value)"
Archivist = <table> {
 DoMigration = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:148
 DeInitialize = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:163
 Warn = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:58
 IsInitialized = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:96
 DeArchive = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:518
 archives = <table> {
 }
 proto = <table> {
 }
 defaultStoreTypes = <table> {
 }
 RegisterDefaultStoreType = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:192
 migrations = <table> {
 }
 Assert = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:48
 buildDate = "@build-time@"
 version = "v2.0.1"
 Initialize = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:102
 Archive = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:511
 RegisterMigration = <function> defined @Journalator\Embeds\Archivist\Archivist.lua:139
 internalVersion = 1
}

**Comment by plusmouse** [comment]
I've pushed a fix that should resolve this issue.
