### ISSUE TITLE
[suggestion] Making Auctionator dependency optional

### ISSUE THREAD

**Issue by tflo** [Auctionator/Journalator#18]
My AH toon runs TSM and Auctionator, and Journalator, my other toons run  Auctionator and Journalator, but when they are "on rest" they only run a minimal add-on set (for loading time), since the only thing they do is the Mission table. And this is without Auctionator.

However, sometimes they sell stuff from their bags (I told them to not do this), and it would be nice to have this captured too in Journalator. I.e., on a toon that has not loaded Auctionator.

Hence, making Journalator work also for vendor stuff on any toon (without regards if Auctionator is running), would be great.

– Tom

**Comment by plusmouse** [comment]
This would be complicated as Journalator references Auctionator stuff 200+ times. Technically I _could_ make a separate UI library for Journalator, but that would add duplicated code, or have them share the library, which would be a significant effort, and probably a source of bugs. For now at least closing this issue as "Won't Fix"

**Comment by tflo** [comment]
This is reasonable.
