### ISSUE TITLE
Reset data

### ISSUE THREAD

**Issue by Magistermomo** [Auctionator/Journalator#22]
Hello,

I've deinstall and reinstall jnr but I wanted the datas to be resets.
How can I do it please ?

thanks

Magistermomo

**Comment by plusmouse** [comment]
Delete this file
```
[WoW Directory]\_retail_\WTF\Account\[Some numbers]\SavedVariables\Journalator.lua
```

**Comment by Magistermomo** [comment]
yesss great !
thank you very much :)
