### ISSUE TITLE
Unreadable font in tables

### ISSUE THREAD

**Issue by nosachev** [Auctionator/Journalator#23]
Please make a normal readable font in the tables. Or the ability to customize it. Thank you.

**Comment by plusmouse** [comment]
Which font? there's a few in use:
![image](https://user-images.githubusercontent.com/60280559/177362700-6b6a6984-1cfd-4462-bce3-0b45d46c0589.png)

**Comment by nosachev** [comment]
![2022-07-05_201737](https://user-images.githubusercontent.com/37359303/177364579-2eada0d0-4166-40b6-9595-377e586e33e4.jpg)

**Comment by nosachev** [comment]
Everything is great now. Thank you so much! All the best to you!!!

![2022-07-05_210306](https://user-images.githubusercontent.com/37359303/177370011-3cebb02e-91df-4b47-b119-5b398671a448.jpg)
