### ISSUE TITLE
Clearing older data

### ISSUE THREAD

**Issue by tflo** [Auctionator/Journalator#24]
Is there a way to clear old data, e.g. anything older than 3 months or 1 month etc.? (Like I can do in TSM.)

With my oldest records being from 175 days ago, the Journalator.lua is still surprisingly small (4.4MB), but in the early days of the add-on there were many bugs, like double counting AH gold mails, or not counting at all, so the older data is probably just misleading clutter I could get rid of.

`/journalator help` doesn’t return any info.

Thank you

– Tom

**Comment by plusmouse** [comment]
There isn't anything in the UI to do that. It shouldn't matter that there's old data, as the time period in the main view will prevent old stuff being displayed unless you want it and the sold/bought tooltips will eventually get new prices.
![image](https://user-images.githubusercontent.com/60280559/177808339-63c2380e-a828-4e57-8fac-f3baaaebca50.png)
