### ISSUE TITLE
[bug] few errors with alpha and stable version 1.7

### ISSUE THREAD

**Issue by pluttotv** [Auctionator/Journalator#30]
```
Message: [ADDON_ACTION_BLOCKED] AddOn 'Journalator' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
Time: Sun Oct  9 03:35:14 2022
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Journalator' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@Interface\FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: <none>
```

```
Message: [ADDON_ACTION_FORBIDDEN] AddOn 'Journalator' tried to call the protected function 'FocusUnit()'.
Time: Sun Oct  9 04:44:04 2022
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'Journalator' tried to call the protected function 'FocusUnit()'.
[string "@Interface\FrameXML\UnitPopupShared.lua"]:148: in function `func'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:944: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: <none>
```

I tried looking those up in the code (both in Auctionator and Journalator) and didn't find any reference.

The first error popped while questing and the second happened on blizzard raid panel (native) when trying to focus a member.

must say amazing addons! 
hope it helps.

**Comment by plusmouse** [comment]
Are you running the Auctionator alphas?

**Comment by plusmouse** [comment]
Also, is this retail or classic?

**Comment by plusmouse** [comment]
I've replicated the bug in Wrath classic, and coincidentally its fixed by a fix for another bug that I fixed yesterday in the alphas.

Pushed the fix to the normal release channels now - you will need both an updated Auctionator and Journalator (as Journalator reuses some components from Auctionator which caused this bug):
[Auctionator-9.2.42-wrath.zip](https://github.com/Auctionator/Journalator/files/9740853/Auctionator-9.2.42-wrath.zip)
[Journalator-1.8.zip](https://github.com/Auctionator/Journalator/files/9740854/Journalator-1.8.zip)

**Comment by pluttotv** [comment]
> I've replicated the bug in Wrath classic, and coincidentally its fixed by a fix for another bug that I fixed yesterday in the alphas.
> 
> Pushed the fix to the normal release channels now - you will need both an updated Auctionator and Journalator (as Journalator reuses some components from Auctionator which caused this bug): [Auctionator-9.2.42-wrath.zip](https://github.com/Auctionator/Journalator/files/9740853/Auctionator-9.2.42-wrath.zip) [Journalator-1.8.zip](https://github.com/Auctionator/Journalator/files/9740854/Journalator-1.8.zip)

thanks! using the new version you linked here still gives me the same errors + this new:

```
Message: [ADDON_ACTION_BLOCKED] AddOn 'Altoholic' tried to call the protected function 'CompactRaidGroup1:unusedFunc()'.
Time: Mon Oct 10 14:52:00 2022
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Altoholic' tried to call the protected function 'CompactRaidGroup1:unusedFunc()'.
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: <none>
```

the most important is this you cant focus a member in raid while having the addons enabled.

**Comment by pluttotv** [comment]
working great with the latest versions.
