### ISSUE TITLE
[Enhancement] Add an API (for at least tooltip data)

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Journalator#32]
Skillet-Classic would like to get information similar to what Journalator provides in tooltips. For example:
```
	local salesRate, failedCount, lastSold, lastBought = Journalator.Tooltips.GetSalesInfo(itemName)
```
I would prefer that the API return the raw data as opposed to already formatted strings.

If there is other information that makes sense to provide in an API, please do so.

Thanks!

**Comment by plusmouse** [comment]
This is done, so closing.
