### ISSUE TITLE
[Request] Work orders

### ISSUE THREAD

**Issue by kayti-wow** [Auctionator/Journalator#35]
Gold earned through work orders is not tracked by Journalator.  Is it possible to add this?

**Comment by plusmouse** [comment]
Not yet. But there is a change in WoW 10.0.5 (currently on the PTR, autodeleting work order mails) that should make it easier for me to add tracking them.

**Comment by plusmouse** [comment]
Hi. I'm working on the crafting orders tracking for Journalator.

What columns would you like in the tab for the view of your historic orders? Ideas that come to mind are "Item name with quality" (and an item link attached), "Incoming gold", "Consortium Cut", "Recipe name".

**Comment by plusmouse** [comment]
Progress update:
![image](https://user-images.githubusercontent.com/60280559/210592672-32f91f7e-e268-4d5a-9540-6568687aa43e.png)

**Comment by kayti-wow** [comment]
That looks great!

**Comment by plusmouse** [comment]
Find this feature in the Fulfilling tab in the latest alpha (available on Curseforge once it finishes processing)
[Journalator-1.16-7-gf922f2b.zip](https://github.com/Auctionator/Journalator/files/10346310/Journalator-1.16-7-gf922f2b.zip)
