### ISSUE TITLE
Tab SaleRates - Unable to sort on "Total"

### ISSUE THREAD

**Issue by nexulh** [Auctionator/Journalator#36]
I get a lua error when trying to sort on the "Total" column in tab "Sale Rates". 

In "Source\DataProviders\SaleRates.lua", the COMPARATORS map is missing a totalPrice entry. 
Adding "totalPrice = Auctionator.Utilities.NumberComparator" into the map solves the problem.

**Comment by plusmouse** [comment]
Thanks for the bug report. The fix will be in the next normal release and available in the next alpha shortly (once it finishes processing).

**Comment by nexulh** [comment]
A similar problem exists in Posting.lua where "deposit" is missing from the COMPARATORS map

**Comment by plusmouse** [comment]
Pushed a fix for that too now 👍
