### ISSUE TITLE
WoW Token gold purchase not tracked

### ISSUE THREAD

**Issue by dylan-dot-tech** [Auctionator/Journalator#37]
Currently, Journalator will track incoming gold from the sale of a WoW Token on the auction house but **not** the outgoing gold used when purchasing said token. If continually trading tokens, this will then to a very inflated net profit. Is this something Journalator is able to track?

**Comment by plusmouse** [comment]
It's theoretically possible, but very awkward to test a feature to track them due to the large amounts of gold involved.

Another solution is adding a "Custom" tab to let a user add in entries for stuff not tracked by Journalator by hand.
