### ISSUE TITLE
Error when looting a container of some kind

### ISSUE THREAD

**Issue by nanjuekaien1** [Auctionator/Journalator#44]
...AddOns/Journalator/Source/Monitor/LootContainers.lua:120: assertion failed!
Count: 3

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: in function `assert'
[string "@Interface/AddOns/Journalator/Source/Monitor/LootContainers.lua"]:120: in function `TagLooted'
[string "@Interface/AddOns/Journalator/Source/Monitor/LootContainers.lua"]:22: in function <...AddOns/Journalator/Source/Monitor/LootContainers.lua:16>

**Comment by plusmouse** [comment]
Do you know what you were looting when this error happened?

**Comment by nanjuekaien1** [comment]
I play in the TW server and make a task in the first picture.

**Comment by plusmouse** [comment]
If you get a way to replicate this bug report back, but for now there isn't much I can do.
