### ISSUE TITLE
(Feature request) Add more information to Fulfilling > Export

### ISSUE THREAD

**Issue by RamyRafik** [Auctionator/Journalator#47]
While Export is a great feature, exported data from Fulfilling is missing key information.
In terms of importance:
1. Order type (Crafting / Recrafting)
2. Crafted Item level
3. Crafted Item rank
4. Optional mats (most importantly, Embellishment)
5. Whether it had an Inspiration proc
6. Profession (Leatherworking, Jewelcrafting, ..etc)

These information can go into additional columns in the Tabular data exported.

**Comment by plusmouse** [comment]
Is there something specific you'll derive from the information? Most uses are covered by just knowing how much gold you got.

**Comment by RamyRafik** [comment]
Yea, I'm using Exported data to see which items (and which levels) are sold the most.
My main goal is to spend my profession knowledge points towards profitable items.

**Comment by plusmouse** [comment]
Progress update
![image](https://user-images.githubusercontent.com/60280559/222901522-7b5009eb-5fa8-4731-a62d-be97588e04af.png)

**Comment by plusmouse** [comment]
Journalator doesn't keep inspiration data, and figuring out what should be displayed for a given usage of optional reagents feels to specific a use case for it to be worth adding it in.

Done 1, 2 and 6 though (and 3 as that can be derived from 2). Closing this issue as complete.
