### ISSUE TITLE
Feature Request: Summarise quantities

### ISSUE THREAD

**Issue by ghost** [Auctionator/Journalator#53]
Hello, please see screenshot.
Is it possible to add a total item qty counter to see how many pcs were looted?
Would be useful.
Sorry if it can bedone somehow, i didnt figure it out yet!
![image](https://user-images.githubusercontent.com/122007087/235541772-3e4e6ab7-d0d5-43f6-9558-10f6ebf5a3a8.png)

**Comment by plusmouse** [comment]
Find this in the latest alpha release, available from Curseforge shortly:
![image](https://github.com/Auctionator/Journalator/assets/60280559/ddb802ad-cc81-462b-bf86-e0ddd81caef8)
[Journalator-1.54-3-gf4721b6.zip](https://github.com/Auctionator/Journalator/files/12316658/Journalator-1.54-3-gf4721b6.zip)
