### ISSUE TITLE
Feature Request: Track gold received in mail

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Journalator#54]
Hello,

Not sure if this makes sense but do you think it's a good idea to add gold received in mail to journalator?
Perhaps a separate tab that lists your mail (that DOESNT come from auction house).
It would list who mail came from, what was in it, and also text contents of mail.

Example why I ask this:
I constantly receive mail from work order customers AFTER i make the order - separately - with a tip.
For example after I make the order, an hour later I get 5k gold in mail with a thank you note.
I want Journalator to store that mail, quantity of gold received, who it was from, and who the sender was.

Sorry if it's already a feature - i couldnt find it :)
Thank you!!!!

**Comment by plusmouse** [comment]
Find this feature in the latest alphas (available from Curseforge or Wago shortly)

**Comment by Rezy942** [comment]
Fantastic! Thanks!
