### ISSUE TITLE
Bug while selling items to NPCs

### ISSUE THREAD

**Issue by Rezy942** [Auctionator/Journalator#55]
Got this bug while selling random items, not sure how to recreate, hope it gives you a hint at least

12x ...ceJournalator/Source/Monitor/VendorItems.lua:14: bad argument #1 to 'DoesItemExist' (Usage: local itemExists = C_Item.DoesItemExist(emptiableItemLocation))
[string "=[C]"]: in function `DoesItemExist'
[string "@Journalator/Source/Monitor/VendorItems.lua"]:14: in function <...ceJournalator/Source/Monitor/VendorItems.lua:13>
[string "@Journalator/Source/Monitor/VendorItems.lua"]:253: in function `UpdateCursorItem'
[string "@Journalator/Source/Monitor/VendorItems.lua"]:188: in function <...ceJournalator/Source/Monitor/VendorItems.lua:187>

Locals:
(*temporary) = <table> {
 GetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:42
 IsBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:60
 SetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:46
 HasAnyLocation = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:64
 Clear = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:29
 IsEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:56
 IsEqualToBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:72
 SetBagAndSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:35
 IsEqualTo = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:88
 GetEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:52
 IsEqualToEquipmentSlot = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:80
 IsValid = <function> defined @FrameXML/ObjectAPI/ItemLocation.lua:68
}

**Comment by plusmouse** [comment]
Had a look. Seems that a Blizzard API returned a value that another Blizzard API disliked.

Do you use a bag addon?

**Comment by Rezy942** [comment]
Yes indeed, Bagnon!
