### ISSUE TITLE
[Wrath] 3.4.1 still needs a shim for GetCurrencyListSize

### ISSUE THREAD

**Issue by Road-block** [Auctionator/Journalator#57]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

An error happens when interacting with some currency vendors.

## Steps to Reproduce

Buy an item from a vendor for currency.

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

```
2x Journalator/Source/Utilities.lua:68: attempt to call field 'GetCurrencyListSize' (a nil value)
[string "@Journalator/Source/Utilities.lua"]:68: in function `GetCurrencyID'
[string "@Journalator/Source/Monitor/VendorItems.lua"]:432: in function <...ceJournalator/Source/Monitor/VendorItems.lua:417>
[string "=[C]"]: in function `BuyMerchantItem'
[string "@FrameXML/StaticPopup.lua"]:280: in function `OnAccept'
[string "@FrameXML/StaticPopup.lua"]:5235: in function `StaticPopup_OnClick'
[string "*StaticPopup.xml:24_OnClick"]:1: in function <[string "*StaticPopup.xml:24_OnClick"]:1>

Locals:
currencyName = "Stone Keeper's Shard"
index = 0
(*temporary) = nil
(*temporary) = "attempt to call field 'GetCurrencyListSize' (a nil value)"
currencyMap = <table> {
}
```

**Comment by Road-block** [comment]
An easy fix is 
```lua
local GetCurrencyListSize = _G.GetCurrencyListSize or C_CurrencyInfo.GetCurrencyListSize
```
at the top of Utilities.lua for example.

**Comment by plusmouse** [comment]
Thanks for the report. I haven't been able to test the currency tracking on Wrath - lacking a character with the right level, location and inventory to do it - so missed that case.

Can you try this version?
[Journalator-1.38-1-g10368f4.zip](https://github.com/Auctionator/Journalator/files/11490747/Journalator-1.38-1-g10368f4.zip)

**Comment by Road-block** [comment]
Seems to be working fine. 

![Clipboard 1](https://github.com/Auctionator/Journalator/assets/109839/ddbaaa7e-4382-484f-a035-ed4dc4826aa5)
In the current Wrath Build if it's any use

**Comment by plusmouse** [comment]
Thanks. I've added the fix to the next alpha release (pending build scripts and processing by Curseforge or Wago)
