### ISSUE TITLE
Bug when collecting mail.

### ISSUE THREAD

**Issue by JoshuaAndrewN** [Auctionator/Journalator#59]
14x Journalator/Source/AddToLogs.lua:6: bad argument #1 to 'insert' (table expected, got nil)
[string "=[C]"]: in function `insert'
[string "@Journalator/Source/AddToLogs.lua"]:6: in function `AddToLogs'
[string "@Journalator/Source/Monitor/CraftingOrderMail.lua"]:72: in function <...Ons/Journalator/Source/Monitor/CraftingOrderMail.lua:69>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:35: in function <FrameXML/ObjectAPI/AsyncCallbackSystem.lua:31>
[string "=[C]"]: ?
[string "=[C]"]: in function `accessor'
[string "@FrameXML/ObjectAPI/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@FrameXML/ObjectAPI/Item.lua"]:326: in function `ContinueOnItemLoad'
[string "@Journalator/Source/Monitor/CraftingOrderMail.lua"]:69: in function `ProcessMail'
[string "@Journalator/Source/Monitor/CraftingOrderMail.lua"]:52: in function <...Ons/Journalator/Source/Monitor/CraftingOrderMail.lua:26>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 time = 1685186549
 itemName = "Pioneer's Writhebark Stave"
 crafterNote = "5172:0:0"
 source = <table> {
 }
 recipeName = ""
 itemLink = "|cff0070dd|Hitem:194892::::::::70:70::13:3:8851:8852:9405:5:28:2164:29:36:30:40:38:8:40:679:::::|h[Pioneer's Writhebark Stave |A:Professions-ChatIcon-Quality-Tier5:17:17::1|a]|h|r"
 commissionPaid = 569400
}
(*temporary) = "table expected, got nil"

**Comment by plusmouse** [comment]
Can you run ```
/dump Journalator.State.Logs.CraftingOrdersSucceeded
/dump Journalator.State.Logs.CraftingOrdersFailed
/dump Journalator.State.Logs.Version
``` and report the output from each?

**Comment by JoshuaAndrewN** [comment]
CraftingOrdersSucceeded = empty result
CraftingOrdersFailed = empty result
Version = [1]=11

**Comment by plusmouse** [comment]
This should resolve the issue
[Journalator-1.41-4-g4bd6194.zip](https://github.com/Auctionator/Journalator/files/11581700/Journalator-1.41-4-g4bd6194.zip)

**Comment by plusmouse** [comment]
That won't fix it actually, just building a new versino

**Comment by plusmouse** [comment]
This will
[Journalator-1.41-5-g7df681c.zip](https://github.com/Auctionator/Journalator/files/11581704/Journalator-1.41-5-g7df681c.zip)

**Comment by plusmouse** [comment]
And again, that's broken. I'm trying to do it too fast. Fingers crossed that this one is it...
[Journalator-1.41-6-g6ad1ccf.zip](https://github.com/Auctionator/Journalator/files/11581705/Journalator-1.41-6-g6ad1ccf.zip)

**Comment by JoshuaAndrewN** [comment]
Hah!  No worries.  Thank you.
