### ISSUE TITLE
Journalator hangs on opening

### ISSUE THREAD

**Issue by sjtyejopemlzn** [Auctionator/Journalator#61]
## Brief Description of Bug

Slash command '/jnr' produces no response. Clicked on the Journalator minimap icon to access add-on. Journalator hangs on opening, no functionality available.  Progress bar is shown, but no progress occurs. 

## Steps to Reproduce

Click Journalator minimap icon.

## Loaded Addons

Auctionator 10.1.7
Journalator 1.43
BugGrabber 10.1.0
BugSack 10.1.2

## Back Trace (LUA Error Output)

1x ...aceJournalator/Source/Archiving/GetRange.lua:11: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Journalator/Source/Archiving/GetRange.lua"]:11: in function `GetRange'
[string "@Journalator_Display/Source/GetCharactersAndRealms.lua"]:15: in function `GetCharactersAndRealms'
[string "@Journalator_Display/Source/Display/FiltersContainer.lua"]:49: in function `UpdateRealmsAndCharacters'
[string "@Journalator_Display/Source/Display/FiltersContainer.lua"]:40: in function <...rnalator_Display/Source/Display/FiltersContainer.lua:39>
[string "=[C]"]: in function `SetShown'
[string "@Journalator_Display/Source/Initialize.lua"]:9: in function `ToggleView'
[string "@Journalator_Display/Source/MinimapIcon.lua"]:39: in function `OnClick'
[string "@BugSack/Libs/LibDBIcon-1.0-51/LibDBIcon-1.0.lua"]:170: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:168>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

6x ...aceJournalator/Source/Archiving/LoadUpTo.lua:64: attempt to compare nil with number
[string "@Journalator/Source/Archiving/LoadUpTo.lua"]:64: in function `IsLoadedUpTo'
[string "@Journalator_Display/Source/MinimapIcon.lua"]:46: in function `OnTooltipShow'
[string "@BugSack/Libs/LibDBIcon-1.0-51/LibDBIcon-1.0.lua"]:73: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:59>

Locals:
minTime = 1685631599
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
frame = nil

![Screenshot (79)](https://github.com/Auctionator/Journalator/assets/136280125/0ceacbe4-e8d9-420e-9cb0-438a357825c9)

**Comment by plusmouse** [comment]
Can you attach your Journalator saved variables file (found at `Wow directory\_retail_\WTF\some numbers\SavedVariables\Journalator.lua`)?

**Comment by plusmouse** [comment]
That location is fine, I mistyped the location, forgot the Account

**Comment by plusmouse** [comment]
Any updates on supplying the saved variables file?

Can you also try disabling all other add-ons (other than Journalator and Auctionator) and see if it's still broken?

**Comment by sjtyejopemlzn** [comment]
I attached the lua file via email reply on Mon 12 Jun:


[image: 1f749b09-01d1-4319-9308-02c1a17e2a7c.png]


I'll try attaching the file to this message. If it doesn't go through, I
can try resending, or use the github platform to send it to you.

I disabled all addons other than Journalator 1.43 and Auctionator 10.1.7,
and the errors still persist.
I upgraded to Journalator 1.44, and I am also getting the errors.

To refine what I'm seeing on my end - I am able to click on the various
tabs of Journalator, but I'm not seeing any information, just a static
'progress' bar in the middle of the screen:

[image: Screenshot (84).png]
[image: Screenshot (85).png]
[image: Screenshot (86).png]

Thank you.

**Comment by plusmouse** [comment]
The email replies don't seem to include any attachments or screenshots. Can you try adding the attachments and screenshots to using the Github interface for the issue?

Can you do the following chat commands and report the output for each one? One of these should output a different value to what I'd expect.
```
/dump JOURNALATOR_LOGS
/dump JOURNALATOR_ARCHIVE_TIMES
/dump Journalator.State.MinTimeLoaded
/dump time()
```

**Comment by sjtyejopemlzn** [comment]
Okay, here are the screenshots I've been trying to send to you:

![Screenshot (84)](https://github.com/Auctionator/Journalator/assets/136280125/5ca1ba6e-c499-46d5-a585-f18c1c70b5d4)
![Screenshot (85)](https://github.com/Auctionator/Journalator/assets/136280125/188184c0-f536-4821-8570-e9058fa2ae52)
![Screenshot (86)](https://github.com/Auctionator/Journalator/assets/136280125/fb4ffccc-1073-491a-99fa-68fba592a6d7)

Saved variable file:

[Journalator.txt](https://github.com/Auctionator/Journalator/files/11761089/Journalator.txt)

Four /dump commands:

[JOURNALATOR_LOGS.txt](https://github.com/Auctionator/Journalator/files/11779707/JOURNALATOR_LOGS.txt)
[JOURNALATOR_ARCHIVE_TIMES.txt](https://github.com/Auctionator/Journalator/files/11779713/JOURNALATOR_ARCHIVE_TIMES.txt)
[Journalator.State.MinTimeLoaded.txt](https://github.com/Auctionator/Journalator/files/11779714/Journalator.State.MinTimeLoaded.txt)
[time().txt](https://github.com/Auctionator/Journalator/files/11779715/time.txt)

**Comment by plusmouse** [comment]
Thanks for the files and screenshots I've found the cause of the problem and fixed it. You can now update to the newest alpha build and it will open correctly
[Journalator-1.44-6-g1967373.zip](https://github.com/Auctionator/Journalator/files/11779788/Journalator-1.44-6-g1967373.zip)

**Comment by plusmouse** [comment]
The issue came from the data being old and the compatibility code having broken since it was written in 2021, I've fixed the compatibility code now.

**Comment by sjtyejopemlzn** [comment]
Thank you for your quick replies and quick fix. Thanks also for your
patience with sorting out the issue with the attachments.
