### ISSUE TITLE
After uninstalling the Auctionator addon, Journalator doesn't work anymore.

### ISSUE THREAD

**Issue by cgsub** [Auctionator/Journalator#63]
It now cause the followig LUA error whenever I do something inventory related, in my case I opened a few JC gem bundles:

**10x Journalator/Source/Utilities.lua:178: attempt to index global 'Auctionator' (a nil value)
[string "@Journalator/Source/Utilities.lua"]:178: in function `GetItemLocationFromGUID'
[string "@Journalator/Source/Monitor/LootContainers.lua"]:346: in function `AddToLogs'
[string "@Journalator/Source/Monitor/LootContainers.lua"]:54: in function <Journalator/Source/Monitor/LootContainers.lua:29>**

And when I tried to open it using /jnr it didn't work and printed:
Journalator: Unable to open display. The Display addon is disabled

I looked in the addon panel and saw that three addons pertaining to Journalator had a dependency on Auctionator.
I'm not sure if this is normal as the addon is not listed as requiring Auctionator installed.

On a side note:
I actually removed Auctionator after the new buy interface made me do too many wrong purchases.
after a while you get used to always click the buy button that kind of constantly pop anyway when you buy something.
To seldom end up realizing that you just paid some material ten time the price that you expected based on the first given price.

Buying often probably rendered me not careful enough. But still, the standard buy interface doesn't cause me this problem.

Edit:

After reinstalling the addon using Curseforge, it seems to work fine without Auctionator now.

**Comment by plusmouse** [comment]
Journalator requires Auctionator for the UI components. The error you got was still a bug, so that's fixed in the latest alpha, but Journalator (Display) will need Auctionator enabled to work.

Side note:
The buy interface has the same number of confirms as the Blizzard interface, its just integrated into the Shopping tab instead. Or is the Auctionator buy interface missing a dialog somewhere?

**Comment by cgsub** [comment]
> Side note: The buy interface has the same number of confirms as the Blizzard interface, its just integrated into the Shopping tab instead. Or is the Auctionator buy interface missing a dialog somewhere?

It's just the price given at first by the interface that can be misleading.

**Comment by plusmouse** [comment]
That price issue should be fixed now (I've just moved the alpha with the fix to a release). There was an issue with the total price being really low in some scenarios.

**Comment by cgsub** [comment]
Alright that is great news, I was missing my shopping lists :)

**Comment by plusmouse** [comment]
As always, report if something goes wrong, there's usually a fix I can add 😄

**Comment by plusmouse** [comment]
I'm going to close this as Auctionator is an intended dependency of Journalator
