### ISSUE TITLE
Journalator error when processing a Public Engineering Crafting Order (on 10.1.5)

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Journalator#64]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

I actually found an Engineering Public Crafting Order I could complete.

## Steps to Reproduce

Create an Engineering Public Crafting Order

## Loaded Addons

Auctionator, Skillet, Journalator, and many others (if you really need the list, let me know and I'll create one).

## Back Trace (LUA Error Output)

2x ...urnalator/Source/Monitor/CraftingOrderFulfilling.lua:16: table index is nil
[string "@Journalator/Source/Monitor/CraftingOrderFulfilling.lua"]:16: in function <...urnalator/Source/Monitor/CraftingOrderFulfilling.lua:13>
[string "=(tail call)"]: ?
[string "@Journalator/Source/Monitor/CraftingOrderFulfilling.lua"]:182: in function `ProcessReagents'
[string "@Journalator/Source/Monitor/CraftingOrderFulfilling.lua"]:198: in function <...urnalator/Source/Monitor/CraftingOrderFulfilling.lua:196>

Locals:
array = <table> {
 1 = <table> {
 }
}
toExclude = <table> {
 1 = <table> {
 }
}
hits = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
}
(for control) = 1
_ = 1
item = <table> {
 quantity = 1
 itemID = 203402
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = <table> {
 quantity = 1
 itemID = 203402
}
(*temporary) = nil
(*temporary) = "table index is nil"

**Comment by b-morgan** [comment]
I completed four public orders and all produced the same error. I then completed two guild orders with no errors.

The public orders were for a Gnomish Voicebox with the customer supplied reagent, a broken Gnomish Voicebox.

**Comment by designadrug** [comment]
I got this same error today when completing inscription treatise through guild orders. Here is an example of the Bug Sack capture: 

1x ...urnalator/Source/Monitor/CraftingOrderFulfilling.lua:16: table index is nil
[string "@Journalator/Source/Monitor/CraftingOrderFulfilling.lua"]:16: in function <...urnalator/Source/Monitor/CraftingOrderFulfilling.lua:13>
[string "=(tail call)"]: ?
[string "@Journalator/Source/Monitor/CraftingOrderFulfilling.lua"]:182: in function `ProcessReagents'
[string "@Journalator/Source/Monitor/CraftingOrderFulfilling.lua"]:198: in function <...urnalator/Source/Monitor/CraftingOrderFulfilling.lua:196>

Locals:
array = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
toExclude = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
hits = <table> {
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
(for control) = 1
_ = 1
item = <table> {
 quantity = 10
 itemID = 190456
}
(*temporary) = nil
(*temporary) = 1
(*temporary) = <table> {
 quantity = 10
 itemID = 190456
}
(*temporary) = nil
(*temporary) = "table index is nil"

**Comment by designadrug** [comment]
I got the same error at the same time for 3 guild treatise and a public enchanting order. The majority of the error capture is identical with only the itemID changing.

**Comment by plusmouse** [comment]
Thanks for the bug report. I've added a fix into 1.52 will be available shortly.
