### ISSUE TITLE
Not Searchable by Player Name Anymore.

### ISSUE THREAD

**Issue by TheHambrick** [Auctionator/Journalator#67]
In previous versions (I tried 1.56 and it works in that version) I was able to search things like crafting orders by player name, but I cannot in 1.58 or 1.59. It only shows the no results found page.

**Comment by plusmouse** [comment]
I've added a fix into 1.60, available here, or for Curseforge shortly.
[Journalator-1.60.zip](https://github.com/Auctionator/Journalator/files/12450471/Journalator-1.60.zip)
