### ISSUE TITLE
[wotlk][skillet classic] Jewelery in Skillet won't get "amount sales" from journalator

### ISSUE THREAD

**Issue by Raithen88** [Auctionator/Journalator#69]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug
Skillet won't get the correct "amount of sold items" in jewelery from journalator.
I've already talked to the author of Skillet (classic) and he sent me here to you. The Skillet classic author is availbale for consulting support.

## Steps to Reproduce
Sell a gem, look it up at skillet, it will show "zero sold items" for this gem.

## Loaded Addons
auctionator, journalator, skillet classic

## Back Trace (LUA Error Output)
No error.

**Comment by Raithen88** [comment]
Edit:
It seems the issue appears only for one character. Engineering and Enchanting on Maincharacter do work. Blacksmith / Engineering and Jewelery on 3rd character won't work.

**Comment by plusmouse** [comment]
Do you have the Journalator (Statistics) addon enabled?
