### ISSUE TITLE
Patch 10.2 LUA error

### ISSUE THREAD

**Issue by zalidthebur** [Auctionator/Journalator#70]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

Popped up after handing in profession quest and receiving the rep and Knowledge item.

## Back Trace (LUA Error Output)

Date: 2023-11-09 21:16:12
ID: 1
Error occured in: Global
Count: 1
Message: Interface/AddOns/Journalator/Source/Utilities.lua line 46:
   table index is nil
Debug:
   [string "=[tsm error check]"]:1: in main chunk
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Journalator/Source/Utilities.lua"]:46: GetFactionID()
   [string "@Interface/AddOns/Journalator/Source/Monitor/Reputation.lua"]:65: ProcessText()
   [string "@Interface/AddOns/Journalator/Source/Monitor/Reputation.lua"]:30:
      ...ace/AddOns/Journalator/Source/Monitor/Reputation.lua:16
Locals:

AddOns:
  NoTaint2, vr221121
  Swatter, v3.4.6837 (SwimmingSeadragon)
  WowheadLooter, v100200
  AchievementsReminder, v
  ACP, v3.5.9
  AddonFactory, v10.2.002
  AdiBags, vv1.10.22
  AdvancedInterfaceOptions, v1.8.10
  AllTheThings, vDF-3.8.0
  Altoholic, v10.2.002
  Armory, vv17.7.0
  ArmoryGuildBank, vv17.7.0
  AskMrRobot, v131
  Auctionator, v10.1.36
  BadBoy, vv10.2.0
  BarrelsOEasy, v1.2.02
  BattlePetDailyTamer, v3.2.10
  BattlePetBattleUITweaks, v2.1.10
  BattlePetBreedID, vv1.25.0
  BlizzMove, vv3.5.18
  BlizzMovePluginRematch, vv1.0.9
  BonusRollPreview, v90000.48-Release
  BtWQuests, v2.34.0
  BtWQuestsBattleForAzeroth, v53.16
  BtWQuestsBattleForAzerothPrologue, v15.7
  BtWQuestsDragonflight, v6.0
  BtWQuestsShadowlandsPrologue, v1.9
  BuyEmAll, v3.5.17
  CanIMogIt, v10.1.5v1.53
  ClassTimer, v2.4.2023.1
  Collectionator, v1.16
  CollectMe, v2.12
  ConfirmSP, v0.21.07.06
  CraftSim, v8.9.2
  CursorTrail, v10.2.0.1
  DataStore, v2023.11.06
  DataStoreAchievements, v2023.11.06
  DataStoreAgenda, v2023.11.06
  DataStoreAuctions, v2023.11.06
  DataStoreCharacters, v2023.11.06
  DataStoreContainers, v10.2.001
  DataStoreCrafts, v10.2.001
  DataStoreCurrencies, v2023.11.08
  DataStoreGarrisons, v2023.11.06
  DataStoreInventory, v2023.11.06
  DataStoreMails, v2023.11.06
  DataStorePets, v2023.11.06
  DataStoreQuests, v10.2.001
  DataStoreReputations, v10.2.001
  DataStoreSpells, v2023.11.06
  DataStoreStats, v2023.11.06
  DataStoreTalents, v10.2.001
  DBMCore, v38d9081
  DBMStatusBarTimers, v38d9081
  DBMVPVEM, vb931ae9
  DeathAlerts, v1.2
  Decursive, v2.7.12
  DejaCharacterStats, vR100107r1
  Dejunk, v1.6.1
  DeModal, v0.7.3
  Details, v#Details.20231109.12027.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyMail, v4.5.4b
  EasyScrap, v34
  ExaltedPlus, v10.0.0-2
  FamilyFamiliarHelper, v2.1.6
  GTFO, v5.5.5
  GuildRosterManager, v1.9901
  GuildBankSnapshots, vv3.5.2
  HandyNotes, vv1.6.17
  HandyNotesArgus, vv0.39
  HandyNotesBattleForAzeroth, v18
  HandyNotesBrokenShore, vv1.52
  HandyNotesDungeonLocations, v2.1a
  HandyNotesMistsOfPandariaTreasures, vv25
  HandynotesPandaria, v1.5.11
  HandyNotesShadowlandsTreasures, vv73
  HandyNotesTreasureHunter, vv33
  HandyNotesWorldMapButton, v100200.01-Release
  InFlightLoad, v10.0.25
  InstanceAchievementTracker, v4.28.0
  InterruptNoSpam, v1.8.14
  Journalator, v1.68
  JournalatorDisplay, v@project-version@
  JournalatorOptionsUI, v@project-version@
  JournalatorStatistics, v@project-version@
  KrowiAchievementFilter, v65.0
  LargerMacroIconSelection, vv1.8.4
  LeatrixPlus, v10.2.00
  LoggerHeadLite, v1.6.4
  LootSpecSwapper, v10.1.7.02
  MasterPlanA, vA
  MaxDps, v10.0.9
  MinimalArchaeology, v10.2.0
  mOnArsWardrobeHelper, v1.27
  MRT, v4800
  Notes, v10.1.6
  NPCTime, v1.0.16
  Ogrilastone, v1.5
  OpenableBeGone, v1.33
  Paste, v1.4.10
  Pawn, v2.8.5
  PetBattleMaster, v10.0.3
  PetTracker, v10.1.1
  PetTrackerJournal, v
  Plater, vPlater-v565.1-Retail
  PointBlankSniper, v5.35
  ProtoformSynthesisFieldJournal, v1.3.8
  QuestPlates, v10.0.2.1
  QuestSounds, v901-2020.10.14
  RaidAchieveFilter, v2.1
  RaiderIO, v10.2.0 (v202311090856)
  RaiderIODBEUF, v
  RaiderIODBEUM, v
  RaiderIODBEUR, v
  RaidSkipper, v1.0.20
  RareScanner, v10.2.0.1
  Rarity, v1.0 (r725-release)
  RarityOptions, v
  Rematch, v5.0.0
  RepSwitch, v10.0.5.24
  SavedInstances, v10.2.0
  SharedMediaCausese, v
  SilverDragon, vv2023.8
  SilverDragonOverlay, vv2023.8
  SilverDragonRangeExtender, vv2023.8
  Simulationcraft, v10.2.0-01
  SoulshapeJournal, v1.2.4
  TalentTreeTweaks, vv1.10.6
  tdBattlePetScript, vv1.9.1
  TellMeWhen, v10.1.6
  TLDRMissions, v10.2-001
  TomTom, vv3.5.3-release
  TradeSkillMaster, vv4.13.14
  TradeSkillMasterAppHelper, vv4.13
  TransmogRoulette, v9.1.0.0
  tullaRange, v10.1.8
  TurnIn, v2.2
  VenturePlan, v4.40b
  WeakAuras, v5.8.4
  WeakAurasCompanion, v5.1.2
  wMarker, v3.0.11
  WorldQuestTab, v10.1.0.0
  WorldQuestTracker, vv10.2.0.484-Retail
  WoWthingCollector, v10.2.0.3
  WQAchievements, vv10.2.0-1
  XanDurability, v5.9
  ZygorGuidesViewer, v9.0
  BlizRuntimeLib_enUS v10.2.0.100200 <none>
  (ck=1070)

**Comment by plusmouse** [comment]
Do you know which faction's rep and which quest this was for?

**Comment by zalidthebur** [comment]
Just did the same quest on a different character. It is the weekly Alchemy proff quest "Examination Week". It gives Valdrakken and Artisan Consortium rep. Happened on the mining one too which is for the same reps.

Also had same error pop when I did a WQ which gave Dragonscale Explorers rep.

Maybe they changed the rep ids with the additoin of the new rep?

**Comment by zalidthebur** [comment]
Hmm. Maybe it's more than just the current expansion rep. Just got the same error when I handed in "The Assault Base". This is alliance side Draenor garrison shipyard quest. Rewarded Hand of the Prophet rep.

**Comment by plusmouse** [comment]
Can you screenshot your currencies tab for the character?

**Comment by plusmouse** [comment]
(I suspect there's a currency in there that's breaking the Journalator code)

**Comment by zalidthebur** [comment]
![z](https://github.com/Auctionator/Journalator/assets/22801358/69047b19-0593-4396-9cd8-ea81d31f9d4a)

**Comment by zalidthebur** [comment]
![z](https://github.com/Auctionator/Journalator/assets/22801358/281ca1af-9129-47d0-8bcb-1eac9f11a56f)

**Comment by plusmouse** [comment]
Got a workaround:
[Journalator-1.68-1-g107c4a9.zip](https://github.com/Auctionator/Journalator/files/13326340/Journalator-1.68-1-g107c4a9.zip)
It looks like a Blizzard API is returning bad values, this will cause them to be safely ignored.

**Comment by zalidthebur** [comment]
Looks like that fixed it. Just did a WQ and no error :-)

**Comment by plusmouse** [comment]
Great. I'll close the issue now - should it reappear comment here and I'll reopen it.
