### ISSUE TITLE
Repairs are always at 0 or 1 silver no matter the actual cost

### ISSUE THREAD

**Issue by MarkKehn** [Auctionator/Journalator#72]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

_Please include a brief description of the bug, including what you were doing, and when it occurred._

## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

This issue is with your last several updates for retail and classic versions. I don't know how long this has been an issue, I only came back to the game a month ago after nine years away, but it's been an issue since I've started playing again and using Journalator.

**Comment by plusmouse** [comment]
The actual cost would be in copper, which is too low to show in the price field, so you see it rounded down to the nearest silver on the display.

The accurate count is kept in the background so the total will be accurate, even if that total is rounded separately after all the coppers are added.
