### ISSUE TITLE
Receiving Gold+Items in Mail but having a nearly full bag, results in Gold not logged 

### ISSUE THREAD

**Issue by negue** [Auctionator/Journalator#73]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

My bag still had some spaces but when I opened all mails - it filled up, the sent gold was added but the mail opening stopped (due to the full bag now) and I think with that it did not recognize the gold. I assume it didn't finish properly.

## Steps to Reproduce

Sent gold and many items to a char, and have the target char then fill up with items^^

## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._

## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by plusmouse** [comment]
Yeah. I can replicate this bug (start with an almost full inventory on the target, then send it items and gold). Will look at fixing it soon.

**Comment by negue** [comment]
Awesome, I'm glad it was reproducable and not some random error that only occurs during fullmoon or something 😬

**Comment by plusmouse** [comment]
Added a fix to the latest alpha. I wasn't able to replicate the issue a second time, but I suspect the issue came from the fail event for the item arriving before the success event for the gold. I've changed it so it won't matter what order they arrive.
