### ISSUE TITLE
Lua error scrolling through Questing tab

### ISSUE THREAD

**Issue by b-morgan** [Auctionator/Journalator#74]
Please include as much of the following information as possible to help me fix the bug:

## Brief Description of Bug

On SoD while scrolling through the data in the Journalator Questing tab there was an occasional Lua error.

## Steps to Reproduce

Have enough quests in the tab to scroll through (my data can be provided if necessary).

## Loaded Addons

SoulSort: enabled
Clique: enabled
Skillet-Classic: enabled
ClassicThreatMeter: enabled
MissingTradeSkillsList: enabled
Auc-Advanced: enabled
KiwiItemInfo: enabled
GamerMaps: enabled
!BugGrabber: enabled
BugSack: enabled
Accountant_Classic: enabled
APIInterface: enabled
Auc-Filter-Basic: enabled
Auc-ScanData: enabled
Auc-Stat-Histogram: enabled
Auc-Stat-iLevel: enabled
Auc-Stat-Purchased: enabled
Auc-Stat-Simple: enabled
Auc-Stat-StdDev: enabled
Auc-Util-FixAH: enabled
Auctionator: enabled
AutoBarClassic: enabled
!!AutoLog: enabled
BetterVendorPrice: enabled
BootyBayGazette: enabled
ClassicCastbars: enabled
ClassicCastbars_Options: enabled
GrimoireKeeper: enabled
IceHUD: enabled
IceHUD_Options: enabled
FishingBuddy: enabled
InFlight: enabled
InFlight_Load: enabled
!MoncaiCompare: enabled
PlayedLog: enabled
Dominos_Encounter: enabled
RealMobHealth: enabled
Scrap: enabled
Scrap_Cleaner: enabled
Scrap_Merchant: enabled
Scrap_Options: enabled
Scrap_Spotlight: enabled
Scrap_Visualizer: enabled
ViragDevTool: enabled
WideQuestLog: enabled
+Wowhead_Looter: enabled
FB_Titan: enabled
TitanClassicAmmo: enabled
TitanClassicBag: enabled
TitanClassicGold: enabled
TitanClassicClock: enabled
TitanClassicLocation: enabled
TitanClassicLootType: enabled
TitanClassicPerformance: enabled
TitanClassicRegen: enabled
TitanClassicRepair: enabled
TitanClassicVolume: enabled
TitanClassicXP: enabled
TitanClassic: enabled
TomTom: enabled
Questie: enabled
DBM-ZG: enabled
DBM-AQ40: enabled
DBM-AQ20: enabled
DBM-Onyxia: enabled
DBM-Naxx: enabled
DBM-MC: enabled
DBM-Party-Classic: enabled
DBM-BWL: enabled
DBM-Azeroth: enabled
DBM-StatusBarTimers: enabled
DBM-GUI: enabled
DBM-DefaultSkin: enabled
DBM-Core: enabled
CopyPasta: enabled
Details: enabled
Details_TinyThreat: enabled
MonkeySpeed: enabled
ClassicLFG: enabled
Details_DataStorage: enabled
Details_Streamer: enabled
FieldGuide: enabled
Guild_Roster_Manager: enabled
Quartz: enabled
WideQuestLogLevels: enabled
Baggins: enabled
PetXPBar: enabled
DBM-Azeroth-BfA: enabled
Scrap_Config: enabled
WhereToGatherClassic: enabled
Altoholic: enabled
Altoholic_Characters: enabled
Altoholic_Grids: enabled
Altoholic_Guild: enabled
Altoholic_Search: enabled
Altoholic_Summary: enabled
DataStore: enabled
DataStore_Auctions: enabled
DataStore_Characters: enabled
DataStore_Containers: enabled
DataStore_Crafts: enabled
DataStore_Inventory: enabled
DataStore_Mails: enabled
DataStore_Quests: enabled
DataStore_Reputations: enabled
ModernTargetFrame: enabled
WeakAurasCompanion: enabled
WeakAurasArchive: enabled
Altoholic_Agenda: enabled
DataStore_Agenda: enabled
DataStore_Spells: enabled
DataStore_Talents: enabled
WeakAuras: enabled
WeakAurasModelPaths: enabled
WeakAurasOptions: enabled
WeakAurasTemplates: enabled
BagSync: enabled
Scrap_Broker: enabled
FB_Broker: enabled
AddonProfiles: enabled
Breakables: enabled
ButtonForge: enabled
Fishbringer: enabled
Postal: enabled
DBM-VPVEM: enabled
Blizzard_CombatText: enabled
MovementSpeed: enabled
WidgetTools: enabled
ChatCopyPaste: enabled
CraftInfoAnywhere: enabled
idTip: enabled
Journalator: enabled
Journalator_Display: enabled
Journalator_OptionsUI: enabled
Journalator_Statistics: enabled
LagBar: enabled
Lemmos_ExpBar: enabled
Profession_Assistance: enabled
WagoAppCompanion: enabled
Blizzard_CompactRaidFrames: enabled

## Back Trace (LUA Error Output)

8x ...alator_Display/Source/ResultsListing/QuestingRow.lua:103: Usage: Item:CreateFromItemLink(itemLinkString)
[string "=[C]"]: in function `error'
[string "@FrameXML/ObjectAPI/Item.lua"]:35: in function `CreateFromItemLink'
[string "@Journalator_Display/Source/ResultsListing/QuestingRow.lua"]:103: in function `OnEnter'
[string "@Auctionator/Source/Components/ResultsListing/Mixins/AuctionatorCell.lua"]:10: in function <...Components/ResultsListing/Mixins/AuctionatorCell.lua:8>

Locals:
(*temporary) = "Usage: Item:CreateFromItemLink(itemLinkString)"

**Comment by plusmouse** [comment]
Added a fix for this into https://github.com/Auctionator/Journalator/commit/d6395c972f2e34ef2b093cf6951762f549ca174e - available from Curseforge as an alpha shortly
