### ISSUE TITLE
Income from Mission Table (SL) missing, or I'm too blind to find it

### ISSUE THREAD

**Issue by tflo** [Auctionator/Journalator#78]
Most of my toons are still doing the SL Mission Table, even more so now in the end phase of DF. The price of Augment Runes is down, but Pet Charms are worthy as always, and also those Gold missions that now return a max of 25 gold or so are _possibly_ still worth doing if you have Anima en masse.

I wanted to use Journalator to check how much I actually get per day/week from these Gold missions, but I can't find this income anywhere.

If I'm not blind as usual and it really isn't there, then please just log it under Loot or Quests, no need to create a separate category. Well, or make a "Miscellaneous" category and put it there along with any future uncategorized income.

**Comment by plusmouse** [comment]
Tracking this is difficult due to the necessity of waiting for/finding a mission with a reward worth tracking to determine the events that give the rewards.

**Comment by tflo** [comment]
The reason for my "or I'm too blind to find it" disclaimer was that I thought I remembered... but actually it was the [Accountant Classic](https://www.curseforge.com/wow/addons/accountant-classic) addon that tracks gold from missions:

<details>
<summary>Screenshot</summary>
Screenshot of Wow at Mar 2, 2024 at 19_02_13-fs8.png
 <img width="764" alt="Screenshot of Wow at Mar 2, 2024 at 19_02_13-fs8" src="https://github.com/Auctionator/Journalator/assets/1410282/89ac78e6-032c-4957-8ebb-2e4c429de1ec">
</details>

I haven't yet checked what they are doing, and usually Accountant Classic is pretty flawed compared to Journalator, but it seems to work.

**Comment by plusmouse** [comment]
Yeah. I wanted to have per-mission records of the gold/items but that was tricky the last time I looked.

**Comment by tflo** [comment]
> per-mission records of the gold/items

It's not a problem with the mission _items_, because the gold is recorded the moment I sell them to the vendor (gear items) or on the AH (Augment Runes). It's just the direct gold income from the gold missions that completely slips through.

**Comment by plusmouse** [comment]
[Journalator-1.79-1-g0df3f76.zip](https://github.com/Auctionator/Journalator/files/14470752/Journalator-1.79-1-g0df3f76.zip)

Try this build (backup your Journalator saved variables first) it should add the mission gold to the summary tab

**Comment by plusmouse** [comment]
I've got missions pending to test it myself, but you might have some sooner

**Comment by tflo** [comment]
Got this error:

```denizenscript
5x Journalator/Source/AddToLogs.lua:6: bad argument #1 to 'insert' (table expected, got nil)
[string "=[C]"]: in function `insert'
[string "@Journalator/Source/AddToLogs.lua"]:6: in function `AddToLogs'
[string "@Journalator/Source/Monitor/MissionTables.lua"]:35: in function <Journalator/Source/Monitor/MissionTables.lua:10>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 source = <table> {
 }
 tableType = 4
 missionID = 2189
 missionName = "Gormling Nibblers"
 money = 375
 time = 1709415020
 itemID = 0
 itemCount = 0
}
(*temporary) = "table expected, got nil"
```

**Comment by plusmouse** [comment]
This should fix that particular bug
[Journalator-1.79-1-g760a610.zip](https://github.com/Auctionator/Journalator/files/14470944/Journalator-1.79-1-g760a610.zip)

**Comment by tflo** [comment]
Summary is empty now, with this error:

<details>
<summary><code>GetProfit.lua:302: attempt to perform arithmetic on field 'moneyIn' (a nil value) </code></summary>

```denizenscript
18x ...faceJournalator_Display/Source/GetProfit.lua:302: attempt to perform arithmetic on field 'moneyIn' (a nil value)
[string "@Journalator_Display/Source/GetProfit.lua"]:302: in function `GetInOut'
[string "@Journalator_Display/Source/DataProviders/SummaryByType.lua"]:31: in function `Refresh'
[string "@Journalator_Display/Source/DataProviders/Display.lua"]:72: in function `callback'
[string "@Journalator/Source/Archiving/LoadUpTo.lua"]:19: in function <...aceJournalator/Source/Archiving/LoadUpTo.lua:5>

Locals:
startTime = 1706836472
endTime = 1709428472
filter = <function> defined @Journalator_Display/Source/DataProviders/SummaryByType.lua:31
result = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
}
Add = <function> defined @Journalator_Display/Source/GetProfit.lua:6
incoming = 0
outgoing = 0
missions = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
(for control) = 1
_ = 1
item = <table> {
 source = <table> {
 }
 tableType = 4
 missionID = 2272
 missionName = "Memory Error"
 money = 0
 time = 1709428431
 itemID = 177699
 itemCount = 1
}
filterItem = <table> {
 itemName = "Memory Error"
 time = 1709428431
 source = <table> {
 }
}
(*temporary) = nil
(*temporary) = Frame {
 0 = <userdata>
 CheckFiltersChanged = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:58
 CharacterDropDown = Button {
 }
 GetFilters = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:156
 GetSearch = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:127
 filters = <table> {
 }
 UpdateMinTime = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:167
 OnShow = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:39
 OnLoad = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:3
 TimePeriodDropDown = Frame {
 }
 earliestRangeTime = 1706836464
 GetTimeForRange = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:80
 SearchFilter = EditBox {
 }
 pending = false
 FactionDropDown = Frame {
 }
 Filter = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:89
 UpdateRealmsAndCharacters = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:48
 ReceiveEvent = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:73
 RealmDropDown = Button {
 }
 OnUpdate = <function> defined @Journalator_Display/Source/Display/FiltersContainer.lua:43
}
(*temporary) = <table> {
 itemName = "Memory Error"
 time = 1709428431
 source = <table> {
 }
}
(*temporary) = true
(*temporary) = "attempt to perform arithmetic on field 'moneyIn' (a nil value)"
```
</details>

**Comment by plusmouse** [comment]
![image](https://github.com/Auctionator/Journalator/assets/60280559/a329164f-9066-41ff-843f-fc8200df631a)
Find this in the latest alpha

**Comment by tflo** [comment]
Yes, it works for me too now. Though I think you should disable the left click script of the Mission Tables entry, as it brings up an empty frame (JNRView with only JNRViewBg, no listing).

Thank you!

**Comment by tflo** [comment]
Result since my last post:

<img width="656" alt="Screenshot of Wow at Mar 5, 2024 at 13_04_45" src="https://github.com/Auctionator/Journalator/assets/1410282/c34b5722-a57d-4868-99c0-21febacbcbae">

(With 13 fully-developed mission tables.)

Well, nothing compared to the 150K+ per week in SL times, but still worth being tracked in Journalator, I think 😄

**Comment by plusmouse** [comment]
Yeah. Thanks for the feedback. I'll add a Mission Tables tab at some point with indicators as to which mission and table provided the gold (the data is stored, the UI is just missing).

**Comment by tflo** [comment]
> which mission

Hmm, pretty irrelevant, I would say, since all the gold missions give roughly the same (23–25 gold). Before the reward nerf, it was different, IIRC.

> which […] table 

Slightly more interesting, but the outcome is predictable (Revendreth tables will be the worst, Night Fae and Maldraxxus the best).

So I would save those database (kilo)bytes for for more interesting stuff 😉

**Comment by plusmouse** [comment]
Well its only 2 numbers, and who knows Blizzard might add good mission tables in the future :P

I won't prioritise adding the UI though, but it'll happen at some point.

**Comment by tflo** [comment]
Yeah, I would love to see mission tables again in future expansions (instead of increasing the gold income from quests/WQs, which seems to be their plan), because missions are something you can always do even in times when you don't have much time to play.
