### ISSUE TITLE
Add up prices in current view

### ISSUE THREAD

**Issue by plusmouse** [Auctionator/Journalator#8]

**Comment by raysmith59** [comment]
I came here to suggest a new tab that has the totals for each item so you can view a top x list in terms of total sales for particular items but an option to sum totals for items in an existing tab would work too.  Would like to see some variation of this implemented!

**Comment by plusmouse** [comment]
Available in the latest alpha (on Curseforge and Wago shortly) 
[Journalator-1.2-1-g9d284f1.zip](https://github.com/Auctionator/Journalator/files/9386545/Journalator-1.2-1-g9d284f1.zip)
