### ISSUE TITLE
"Last Bought" tooltip info missing for items in BMAH frame

### ISSUE THREAD

**Issue by tflo** [Auctionator/Journalator#80]
I noticed that for items in the BMAH frame the Journalator "Last Bought" tooltip info is missing:

<img width="941" alt="missing-fs8" src="https://github.com/Auctionator/Journalator/assets/1410282/b0604227-4fdb-461a-8bf7-775c00e1d6da">
 

I have all tooltips enabled in the settings, and there is definitely a record for a bought item in Journalator's db:

<img width="1476" alt="jrnEntry-fs8" src="https://github.com/Auctionator/Journalator/assets/1410282/1a802e3a-18a5-4164-8945-9772b03e3acf">
 
For items in the other AH frame, the info is displayed.

**Comment by tflo** [comment]
OK, I've just seen a Journalator tooltip on a not-BoP battle pet item in the BMAH, with auction data from the normal AH apparently:

<img width="585" alt="Screenshot of Wow at Mar 14, 2024 at 12_30_20" src="https://github.com/Auctionator/Journalator/assets/1410282/c55e40f6-e387-4f00-8ea9-9a6079a4a8d3">


So the problem doesn't seem to be the BMAH frame, but rather the tooltip is missing if the item does not exist in the normal AH? (Like the BoP mount item from above.)

**Comment by plusmouse** [comment]
Its probably because the BMAH item has a different item ID to the item purchased from the AH

**Comment by tflo** [comment]
Well, it's not an issue if it's not in the tooltip, I can always search in Journalator when I want to know when I bought an item and how much I did pay. (And there's also the TSM tooltip that shows me the info, pic 1.). I was just wondering if this was an oversight.

**Comment by plusmouse** [comment]
Having a look at the code there's a `IsAuctionableItem(itemLink)` check so that would be why the item is excluded from the tooltip.

I wasn't expecting BMAH purchases to get recorded, so its an oversight that they did, rather than an oversight that the price is in the tooltip.

I'll leave BMAH purchases to keep getting recorded though until I can move them to their own tab.

**Comment by plusmouse** [comment]
Added the price to the tooltip in the latest alphas

**Comment by tflo** [comment]
> I wasn't expecting BMAH purchases to get recorded, so its an oversight that they did

Oh, besides WoW tokens, BMAH purchases is where most of my gold goes! So it would be fatal if exactly that wasn't recorded by Journalator 😉
