### ISSUE TITLE
Higher frameStrata

### ISSUE THREAD

**Issue by tflo** [Auctionator/Journalator#81]
I think it would be convenient to have the Journalator window at a higher frameStrata, so that it is above the TSM/AH frame. The reason for this idea is that I often find myself browsing the journal while TSM is doing a lengthy AH scan:

<details>
<summary>As it is now</summary>
<img width="1028" alt="jnr bad-fs8" src="https://github.com/Auctionator/Journalator/assets/1410282/3c288341-86ab-490e-b60e-d39f0f576ead">
</details> 

<details>
<summary>frameStrata 'HIGH'</summary>
<img width="1032" alt="jnr good-fs8" src="https://github.com/Auctionator/Journalator/assets/1410282/3d163309-e57d-4d8a-85bd-ac1fd7fbe60f">
</details> 

(The loading progress bar must be at 'DIALOG' then.)

The Journalator window is something you typically open when you actually want to see it (not something you keep open most of the time), so a relatively high strata would be justified, IMHO.

Thanks for considering.

**Comment by plusmouse** [comment]
As far as I'm concerned this is a TSM bug, as they shouldn't adopt such a high frame strata, which doesn't interact well with other Blizzard frames.

**Comment by tflo** [comment]
You are right, it's just TSM that is on HIGH (I thought it was also the normal AH frame, but that's just a the higher layer if Journalator is already on screen).

Gonna try to fix it in my TSM then (which is already tweaked left and right 🤪).

**Comment by tflo** [comment]
After your reply, I followed your suggestion and fixed the strata of my TSM (high --> medium), which solved the problem without any glitches.

A few weeks ago it seems you added a conditional to Baganator, to set Baganator's strata to "HIGH" if TSM is loaded. So, now I have a similar problem with Journalator and Baganator as I had before with Journalator and TSM 🙃 (without my local TSM fix I would have the Baganator strata problem _in addition_ to TSM.)

So maybe at the end wouldn't it be the better solution to set Journalator's strata to "HIGH"? (You could do it also with a TSM conditional, like with Baganator's strata.) It would then be better also for TSM users who don't modify their TSM copy.

And, as mentioned in the OP, I think for an addon like Journalator, which usually is only on screen for a short time (when the user looks something up), even an unconditional "HIGH" strata _could_ be justified.

BTW, also removing the "clamp to screen" could help to make the handling of the Journalator frame less clunky, since the frame is quite large horizontally (more than half of my screen width).

**Comment by plusmouse** [comment]
Done the conditional now. Find it in the latest alpha once CF approves it.
